/**
 * Builds audioMap.js from existing .mp3 files + narration scripts
 * Maps: text string (lowercase, trimmed) → mp3 filename
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// All phrases — key matches filename, text matches on-screen narration
const phrases = [
  { key: 'intro_welcome', text: 'Welcome to Grade 3 Mathematics — Parallel and Perpendicular Lines! Join us on an exciting journey through graphs, straight lines, and data. Let\'s begin!' },
  { key: 'wonder_q1', text: 'Hmm... I wonder... The class voted for their favourite fruit. How can we show who won without counting one by one every time?' },
  { key: 'wonder_hint', text: 'What if there were a clever way to draw it? We might need to draw a graph with straight, matching lines!' },
  { key: 'story_1', text: "Emma is running a Fruit Fair stall at school. She asks her classmates which fruit they like best — Apple, Mango, Grapes, or Orange. She makes a tally chart to record every vote. But the list of numbers is hard to read at a glance! She says: I need a graph to show who is winning!" },
  { key: 'story_2', text: "Emma draws one line going sideways — that is the category axis. Then she draws one line going straight up. They meet at a perfect square corner, just like the walls of a room. Two lines that meet at a right angle are called perpendicular lines!" },
  { key: 'story_3', text: "Now Emma draws a bar for each fruit. Every bar stands straight up from the category axis. Each bar is perfectly straight, and none of the bars lean into each other. Lines that are always the same distance apart and never cross are called parallel lines!" },
  { key: 'story_4', text: "Emma's graph is finished! Because the axes are perpendicular and the bars are parallel, it is very easy to read. She can see straight away which fruit got the most votes. The scale says 1 square equals 2 votes, so she counts squares and multiplies! Mango wins — 14 votes!" },
  { key: 'sim_a_intro', text: 'Station A — Line Spotter! Tap each pair of glowing lines. Are they parallel, perpendicular, or neither?' },
  { key: 'sim_b_intro', text: 'Station B — Axis Architect! Drag the sideways line first, then the up-and-down line. Watch for the little square corner — that means your axes are perpendicular!' },
  { key: 'sim_c_intro', text: 'Station C — Bar Builder! Slide each bar up to match the votes. Keep every bar parallel to its neighbours so the graph stays fair to read.' },
  { key: 'sim_d_intro', text: 'Station D — Graph Detective! Something is wrong with this graph. Tap the part that breaks the rules of parallel and perpendicular lines.' },
  { key: 'sim_perp_snap', text: 'Perfect! Your axes are perpendicular — they meet at a perfect corner, just like the walls of a room!' },
  { key: 'sim_parallel_snap', text: 'Gridline snapped into place — parallel and evenly spaced!' },
  { key: 'sim_axis_done', text: 'All gridlines placed! They are all parallel and evenly spaced. Your axis frame is complete!' },
  { key: 'sim_tilt_block', text: 'Bars must stay parallel to be fair to compare!' },
  { key: 'sim_bar_done', text: 'Excellent bar graph! All bars are parallel — great work!' },
  { key: 'play_intro', text: 'Play phase! Choose your world. Earn stars and XP!' },
  { key: 'play_correct_1', text: 'Perfectly plotted! Well done!' },
  { key: 'play_correct_2', text: 'Correct! Great work!' },
  { key: 'play_correct_3', text: 'Excellent! You got it!' },
  { key: 'play_correct_4', text: 'Brilliant answer!' },
  { key: 'play_incorrect_1', text: 'Not quite! Check the graph carefully.' },
  { key: 'play_hint_1', text: 'Here is your first hint — look at the highlighted part of the graph.' },
  { key: 'play_hint_2', text: 'Here is your second hint — think about the scale value and count again.' },
  { key: 'play_badge', text: 'Badge unlocked! Congratulations!' },
  { key: 'world_0', text: 'World 1 — Fruit Fair! Answer 10 questions about fruit vote graphs. Scale is 1. Good luck!' },
  { key: 'world_1', text: 'World 2 — Pet Parade! Which pet got the most votes? Use the bar graph to find out!' },
  { key: 'world_2', text: 'World 3 — Sports Day Scores! Read graphs with scale 2. Go, team!' },
  { key: 'world_3', text: 'World 4 — Weather Watch! How much sunshine? Read the bar graph carefully!' },
  { key: 'world_4', text: "World 5 — Toy Box Tally! Scale is 5 in this world. Count carefully!" },
  { key: 'world_5', text: "World 6 — Book Nook Graphs! How many books were borrowed? Let's find out!" },
  { key: 'world_6', text: 'World 7 — Snack Survey! Big numbers — scale is 10. You can do it!' },
  { key: 'world_7', text: 'World 8 — Garden Grid! Focus on parallel and perpendicular line identification!' },
  { key: 'world_8', text: 'World 9 — Star Gazers Chart! Hard questions with scale 10. Aim for the stars!' },
  { key: 'world_9', text: 'World 10 — Grand Graph Gallery! Mixed questions and two-step word problems. Show what you know!' },
  { key: 'q1_001', text: 'Look at the bar graph. How many students chose Mango?' },
  { key: 'q1_002', text: 'How many students chose Apple?' },
  { key: 'q1_003', text: 'The bar graph shows class pets. How many students chose Dog?' },
  { key: 'q1_004', text: 'Sports Day results — how many students chose Football?' },
  { key: 'q1_005', text: 'How many students chose Badminton on Sports Day?' },
  { key: 'q1_006', text: 'The weather chart shows hours of sunshine. How many hours on Thursday?' },
  { key: 'q1_007', text: 'Library books borrowed — how many Adventure books?' },
  { key: 'q1_008', text: 'Snack survey — how many students chose Pizza?' },
  { key: 'q1_009', text: 'CCA sign-ups — how many students joined Music?' },
  { key: 'q1_010', text: 'Star-chart rewards — how many stars on Thursday?' },
  { key: 'q2_001', text: 'Which pair of lines meet at a right angle — are perpendicular?' },
  { key: 'q2_002', text: 'Which pair of lines are parallel — never meet, always same distance apart?' },
  { key: 'q2_003', text: 'In a bar graph, which lines are perpendicular?' },
  { key: 'q2_004', text: 'Which lines in a bar graph are parallel to each other?' },
  { key: 'q2_005', text: 'A shelf and the side panel of a bookcase — what is their relationship?' },
  { key: 'q2_006', text: 'Two white stripes on a zebra crossing — what is their relationship?' },
  { key: 'q2_007', text: 'A ladder rung and the ladder rail — are they parallel, perpendicular, or neither?' },
  { key: 'q2_008', text: 'Two bars on a bar graph — are they parallel, perpendicular, or neither?' },
  { key: 'q2_009', text: 'A leaning book on a shelf and the horizontal shelf — are they parallel, perpendicular, or neither?' },
  { key: 'q2_010', text: 'Oliver says the x-axis and y-axis of every bar graph are perpendicular. Is he correct?' },
  { key: 'q3_001', text: 'Each fruit symbol equals 2 votes. How many votes did Mango get?' },
  { key: 'q3_002', text: 'Each paw symbol equals 2 students. How many students chose Dog?' },
  { key: 'q3_003', text: 'Each football equals 2 students. How many chose Badminton?' },
  { key: 'q3_004', text: 'Each sunshine symbol equals 5 hours. How many hours of sunshine on Wednesday?' },
  { key: 'q3_005', text: 'Each book symbol equals 5 books. How many Science books were borrowed?' },
  { key: 'q3_006', text: 'Each strawberry equals 5 votes. How many votes did Orange get?' },
  { key: 'q3_007', text: 'Each pencil equals 5 items. How many Erasers are in the box?' },
  { key: 'q3_008', text: 'Each star equals 10 students. How many students joined Music CCA?' },
  { key: 'q3_009', text: 'Each grape symbol equals 10 votes. How many votes did Orange get?' },
  { key: 'q3_010', text: 'Each star equals 10 stars. How many reward stars were earned on Thursday?' },
  { key: 'q4_001', text: 'Which fruit got the FEWEST votes?' },
  { key: 'q4_002', text: 'Which fruit got the MOST votes?' },
  { key: 'q4_003', text: 'Which pet did the FEWEST students choose?' },
  { key: 'q4_004', text: 'Which sport had the MOST votes on Sports Day?' },
  { key: 'q4_005', text: 'Which sport had the FEWEST votes?' },
  { key: 'q4_006', text: 'On which day was there the MOST sunshine?' },
  { key: 'q4_007', text: 'Which type of book was borrowed the LEAST?' },
  { key: 'q4_008', text: 'Which snack was chosen by the MOST students?' },
  { key: 'q4_009', text: 'Which CCA had the FEWEST sign-ups?' },
  { key: 'q4_010', text: 'Which fruit had the fewest votes in the grand poll?' },
  { key: 'q5_001', text: 'Emma collected 9 stickers on Monday and 6 stickers on Tuesday. How many stickers did she collect in total?' },
  { key: 'q5_002', text: 'Oliver sold 15 tickets on Monday and 9 on Tuesday. How many tickets did he sell in total?' },
  { key: 'q5_003', text: 'Sophie scored 12 goals this week and 8 last week. How many goals in total?' },
  { key: 'q5_004', text: 'James recycled 24 bottles in Week 1 and 18 in Week 2. How many bottles did he recycle altogether?' },
  { key: 'q5_005', text: 'Liam earned 35 points on Monday and 27 on Tuesday. How many points did he earn in all?' },
  { key: 'q5_006', text: 'Ava planted 18 seedlings on Saturday and 24 on Sunday. How many seedlings did she plant in total?' },
  { key: 'q5_007', text: 'Noah borrowed 15 books in March and 22 books in April. How many books did he borrow altogether?' },
  { key: 'q5_008', text: 'Isabella counted 46 votes for Pizza and 34 votes for Burgers. How many votes were there in total?' },
  { key: 'q5_009', text: 'William collected 57 cans on Day 1 and 43 cans on Day 2 for the recycling drive. How many cans in all?' },
  { key: 'q5_010', text: 'Charlotte earned 63 XP on Monday and 37 XP on Tuesday in the reading challenge. What is her total XP?' },
  { key: 'q6_001', text: 'True or False: The bars in a bar graph are parallel to each other.' },
  { key: 'q6_002', text: 'True or False: The horizontal axis and vertical axis of a graph are parallel.' },
  { key: 'q6_003', text: 'True or False: Two gridlines on the value axis of a bar graph are parallel.' },
  { key: 'q6_004', text: 'True or False: A bar and the horizontal axis of a graph are perpendicular.' },
  { key: 'q6_005', text: 'True or False: Railway tracks are an example of parallel lines.' },
  { key: 'q6_006', text: 'True or False: The rungs of a ladder and the rails of the ladder are perpendicular.' },
  { key: 'q6_007', text: 'True or False: You can make a correct bar graph with bars that lean at different angles.' },
  { key: 'q6_008', text: 'True or False: Perpendicular lines always meet at exactly 90 degrees.' },
  { key: 'q6_009', text: 'True or False: Parallel lines will eventually cross if you extend them far enough.' },
  { key: 'q6_010', text: 'True or False: In a correct picture graph, each row of symbols represents data proportional to the scale key.' },
  { key: 'q7_001', text: 'Which description matches: Mango is greater than Apple, Apple is greater than Grapes?' },
  { key: 'q7_002', text: 'Which description matches: Dog has twice as many votes as Rabbit?' },
  { key: 'q7_003', text: "Which description matches: Books equals Pencils, Pencils are greater than Erasers?" },
  { key: 'q7_004', text: 'Which graph shows: Football 30, Swimming 20, Badminton 25, Basketball 15, scale equals 5?' },
  { key: 'q7_005', text: "Oliver says: Thursday has the most sunshine, Monday the least. Which graph matches?" },
  { key: 'q7_006', text: 'Which description fits: Toys — Cars equal 10, Dolls equal 15, Blocks equal 5, Trains equal 20?' },
  { key: 'q7_007', text: 'Library: Science books borrowed 3 times as many as Art. Which matches?' },
  { key: 'q7_008', text: 'Which graph correctly shows perpendicular axes AND parallel bars?' },
  { key: 'q7_009', text: 'CCA sign-ups — Music has 3 times the sign-ups of Drama. Which matches if Drama equals 30?' },
  { key: 'q7_010', text: 'Grand Gallery: Orange is greater than Apple, Apple is greater than Grapes. Which correctly matches a bar graph with scale 10?' },
  { key: 'q8_001', text: 'Add up all the fruit votes in the table. What is the total?' },
  { key: 'q8_002', text: 'How many students voted for pets in total?' },
  { key: 'q8_003', text: 'How many students voted for sports in total?' },
  { key: 'q8_004', text: 'What is the total sunshine hours for the whole week?' },
  { key: 'q8_005', text: 'How many books were borrowed in total from the library?' },
  { key: 'q8_006', text: 'How many toys are in the toy box altogether?' },
  { key: 'q8_007', text: 'How many students voted in the snack survey in total?' },
  { key: 'q8_008', text: 'How many CCA sign-ups were there in total?' },
  { key: 'q8_009', text: 'How many stars were earned across the whole week?' },
  { key: 'q8_010', text: 'Grand Gallery — what is the total of all fruit votes combined?' },
  { key: 'q9_001', text: 'How many MORE votes did Mango get than Grapes?' },
  { key: 'q9_002', text: 'How many more students chose Dog than Rabbit?' },
  { key: 'q9_003', text: 'How many more students chose Football than Badminton?' },
  { key: 'q9_004', text: 'How many more students chose Football than Swimming?' },
  { key: 'q9_005', text: 'How many more hours of sunshine were there on Thursday than Monday?' },
  { key: 'q9_006', text: 'How many more Adventure books were borrowed than Science books?' },
  { key: 'q9_007', text: 'How many more Trains are in the box than Blocks?' },
  { key: 'q9_008', text: 'How many more students chose Pizza than Noodles?' },
  { key: 'q9_009', text: 'How many more students signed up for Music than Drama?' },
  { key: 'q9_010', text: 'How many more votes did Orange get than Grapes in the Grand Gallery?' },
  { key: 'q10_001', text: 'Which picture shows correctly drawn perpendicular axes for a bar graph?' },
  { key: 'q10_002', text: "Emma drew her bar graph axes at a 45-degree angle. Is this correct?" },
  { key: 'q10_003', text: 'Which is true about the value axis of a correctly drawn bar graph?' },
  { key: 'q10_004', text: "Oliver's graph has gridlines at 0, 5, 12, 20, 25. Is this a correct scale?" },
  { key: 'q10_005', text: 'Which axis diagram shows bars that are parallel to each other?' },
  { key: 'q10_006', text: "Sophie's bar graph has axes at a right angle. Is this perpendicular?" },
  { key: 'q10_007', text: 'Which shows correctly parallel gridlines for a bar graph?' },
  { key: 'q10_008', text: 'A graph has axes meeting at 88 degrees instead of 90 degrees. What is the problem?' },
  { key: 'q10_009', text: "Lucas draws a bar graph where the category axis is vertical and the value axis is horizontal. Are they still perpendicular?" },
  { key: 'q10_010', text: 'In a correctly drawn bar graph with scale equal to 10, which set of gridline labels shows evenly spaced parallel gridlines?' },
  { key: 'reflect_congrats', text: 'Journey Complete! You finished all five phases! Fantastic work! You are a true Graph Champion!' },
  { key: 'reflect_excellent', text: 'Excellent! You really understand parallel and perpendicular lines in graphs!' },
  { key: 'reflect_good', text: 'Great effort! Keep practising to master all 10 worlds!' },
  { key: 'reflect_q', text: 'What did you learn about lines in a graph today?' },
];

const AUDIO_DIR = path.join(__dirname, '..', 'public', 'assets', 'audio');
const map = {};

for (const p of phrases) {
  const filepath = path.join(AUDIO_DIR, `${p.key}.mp3`);
  if (fs.existsSync(filepath)) {
    const k = p.text.trim().toLowerCase().replace(/\s+/g, ' ');
    map[k] = `${p.key}.mp3`;
  }
}

const outPath = path.join(__dirname, '..', 'src', 'utils', 'audioMap.js');
const content = `// Auto-generated audio map — ${Object.keys(map).length} entries\nexport const audioMap = ${JSON.stringify(map, null, 2)};\nexport default audioMap;\n`;
fs.writeFileSync(outPath, content);
console.log(`✅ audioMap.js written with ${Object.keys(map).length} entries`);
